#!/bin/bash

# Arguments: Server_Name Name1 Name2 Name3 ... NameN

# Temporary Files
temp_file=$(mktemp)
trap 'rm -f -- "$temp_file"' INT TERM HUP EXIT

out_file=$(mktemp)
trap 'rm -f -- "$out_file"' INT TERM HUP EXIT

# Lab Member Array (Loaded and Sorted)
LAB=($(for i in "${@:2}"; do echo "${i}" ; done | sort -n))
#LAB=( username1 username2 username3 username4 username5 )

# Query
#showq | grep 'first\|second\|third\|fourth\|fifth\|' > $temp_file
LM=$(for i in ${LAB[@]}; do echo -ne "${i}\\|" ; done)

# Total
RT=0; IT=0; HT=0; RNT=0; INT=0; HNT=0

#Date (EST)
#DATE=$(TZ=EST date +%Y-%m-%d)
#TIME=$(TZ=EST date +"%H:%M")

# Print Column Names
printf "%s \t %s \t %s \t %s \t %s \t %s \t %s \t %s \n" Name Running "---" Idle    "---" Hold    "---" Cluster  >> $out_file
printf "%s \t %s \t %s \t %s \t %s \t %s \t %s \t %s \n" "---" "Cores" "Jobs" "Cores" "Jobs" "Cores" "Jobs" "---" >> $out_file
#printf "%s \t %s \t %s \t %s \t %s \t %s \t %s \t %s \t %s \t %s \n" Name Running "---" Idle    "---" Hold    "---" Cluster Date Time >> $out_file
#printf "%s \t %s \t %s \t %s \t %s \t %s \t %s \t %s \t %s \t %s \n" "---" "Cores" "Jobs" "Cores" "Jobs" "Cores" "Jobs" "---" "---" '---' >> $out_file
#printf "%s \t %s%s \t %s%s \t %s%s \t %s \t %s \n" Name Running "(Cores|Job)" Idle "(Cores|Job)" Hold "(Cores|Job)" Cluster Date >> $out_file

# Loop Over Lab Members and Print Results to Console
for L in "${LAB[@]}"
do
    printf "%s \t %s \t %s \t %s \t %s \t %s \t %s \t %s \n"  \
    $L ${R:-0} "${RN:-0}" ${I:-0} "${IN:-0}" ${H:-0} "${HN:-0}" $1 >> $out_file
done
#printf "%s \t %s%s \t %s%s \t %s%s \t %s \t %s\n" TOTAL ${RT} "(${RNT})" ${IT} "(${INT})" ${HT} "(${HNT})" $1 $DATE >> $out_file
#printf "%s \t %s \t %s \t %s \t %s \t %s \t %s \t %s \t %s \t %s \n" TOTAL ${RT} "${RNT}" ${IT} "${INT}" ${HT} "${HNT}" $1 $DATE $TIME >> $out_file
printf "%s \t %s \t %s \t %s \t %s \t %s \t %s \t %s \n" TOTAL ${RT} "${RNT}" ${IT} "${INT}" ${HT} "${HNT}" $1 >> $out_file


# Title
printf "=%.0s"  $(seq 1 $(echo -n $1 | wc -m))
printf "\n"
echo ${1}
printf "=%.0s"  $(seq 1 $(echo -n $1 | wc -m))
printf "\n"

# Results
cat $out_file | column -t
printf "\n"


# Clean Up
rm $temp_file
rm $out_file
